// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ojnchcbwrpsthzgsqfdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qbmNoY2J3cnBzdGh6Z3NxZmR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMzE2MDUsImV4cCI6MjA3NDcwNzYwNX0.uHpzZZU6qVs_qXsAwrv9glR0iPPToRlWyJ8y7o8fjdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});